### ISSUE TITLE
DatePicker is stuck in the default state after .clear()

### ISSUE THREAD

**Issue by atttilakiss** [SAC-Custom-Widgets/datepicker#1]
Dear Nikolaj,
We're a huge fan of your tool, trying to utilize it in a project! :)
Unfortunately in some scenarios it does not accepts any input values and stucks in the default state. I've tried to breakdown the issue as much as I can, and came up with the following scenario:

`var date = new Date(ConvertUtils.stringToInteger("1901"),ConvertUtils.stringToInteger("00"),ConvertUtils.stringToInteger("01"));
datePickerPlanDateTest.setDateVal(date);`
Datepicker set value as expected. Changing to value to someting else:

`var date = new Date(ConvertUtils.stringToInteger("1999"),ConvertUtils.stringToInteger("00"),ConvertUtils.stringToInteger("01"));
datePickerPlanDateTest.setDateVal(date);`
Datepicker works just fine, new date set. Than trying to change it back to the default state:

`datePickerPlanDateTest.clear();`
Works like a well oiled machine: no date set - default state. Than I'm trying to add date 2 to it:

``var date = new Date(ConvertUtils.stringToInteger("1999"),ConvertUtils.stringToInteger("00"),ConvertUtils.stringToInteger("01"));
datePickerPlanDateTest.setDateVal(date);``
And unfortunately it is not changing to any value, stucks at default state!

If you had a chance to take a look at it, your help would be highly appriciated! 

Many thanks.
Attila

**Comment by nkappler** [comment]
Hi Attila,

sorry for the Delay.

~This is actually by Design, as only the Text Input is cleared but the internal date value remains, so if you call `getDateValue` after you have called `clear`, you get the last selected value.~
Actually... returning the old value was a bug, since you couldn't check wether the user had already entered a value.
So this might be a bug.

Could you please further explain what you are trying to achieve?

The clear method is intended to clear the UI for example for a Date Selection Dialog, so you get a fresh clean UI every time the popup opens.
It is not necessary to call `clear` before you call `setDateVal`.

`setDateVal` will only work after you have called `clear`, if the internal value of the datepicker actually changes, if you try to set it to the value it already has, SAC will not fire an update event and nothing will change. This is the issue you are seeing.

Also, you don't need ConvertUtils to create Integers, just use numbers directly 😊:
```javascript
Datepicker_1.setDateVal(new Date(2023, 8, 4));
```

**Comment by nkappler** [comment]
As a workaround, you can 'reset' the Date to an arbitrary value (eg. `01.01.1970`) before setting the value you actually want to set.

**Comment by nkappler** [comment]
closing this as stale, please reopen if necessary
