### ISSUE TITLE
DatePicker selects wrong year after selecting date

### ISSUE THREAD

**Issue by jefbaeyens** [SAC-Custom-Widgets/datepicker#2]
DatePicker selects wrong year after selecting date (e.g. 30th of December 2024 -> shows 30th of December 2025).
This is likely because 29-30-31 of december already fall into **week 1** of 2025.

Please fix this bug as it is confusing users. :)

**Comment by nkappler** [comment]
Hi Jef,

thanks for reporting. I was able to reproduce your issue:
![image](https://github.com/SAC-Custom-Widgets/datepicker/assets/9429273/83c2b109-d105-4d34-af3c-966711b14817)

It seems that this is somehow related to the date formatting, as it shows the correct date when the format is set to automatic:
![image](https://github.com/SAC-Custom-Widgets/datepicker/assets/9429273/d5475714-e80e-40a0-8bf9-9c4cf95829da)
![image](https://github.com/SAC-Custom-Widgets/datepicker/assets/9429273/916553b5-7249-48d9-8432-ccd23b857698)

Unfortunately, my custom widget is basically just a wrapper for the UI5 control, which seems to suffer from this issue, too.
I've found several related issues, some already resolved, some stale:
https://github.com/SAP/ui5-webcomponents-react/issues/674
https://github.com/SAP/ui5-webcomponents/issues/2202
https://github.com/SAP/openui5/issues/3182

Switching to the UI5 webcomponent, where the bug seems to be fixed already, would require to rewrite the custom widget from scratch and I don't have the time to do this currently.

I'll open up a new UI5 bug and link it here, however keep in mind that it will take quite some time until a potential fix will arrive at SAP Analytics Cloud.

I don't think there's anything I can do to my custom widget to fix this.
For now, I suggest to switch the date format to automatic.

If that's not sufficient, you could also add a label to your application/story and show a message/warning with the correct date, if `DEC 31st` is selected. `getDateVal` returns the correct date, it is just a UI formatting issue.

**Comment by nkappler** [comment]
I will also try different approaches for the selectable date formats, but I'm not sure if it will help

**Comment by nkappler** [comment]
I've done some more research and found out that this doesn't happen when the language is set to german.

I've created a new issue for UI5: https://github.com/SAP/openui5/issues/3854

**Comment by jefbaeyens** [comment]
Hi Nikolaj,

Can you check the reply on your UI5 incident?
It could maybe be an easy fix if we format with yyyy instead of YYYY. :)

**Comment by nkappler** [comment]
Hi Jef,

apologies for the delay.
I've just published version 2.5.2, fixing the issue.
Please download it at [widgets.nkappler.de/datepicker](https://widgets.nkappler.de/datepicker/)

![image](https://github.com/SAC-Custom-Widgets/datepicker/assets/9429273/d3dcd40b-94c7-4919-90de-4ab7323e4b32)
